# Exercises Deep Learning
First Lecture

## Basic Tensor Operations


In [96]:
import torch
import torch.nn as nn
import numpy as np

In [97]:
x = torch.Tensor(2, 3, 4)

Different ways to create tensors:
- ```torch.zeros```: Creates a tensor filled with zeros
- ```torch.ones```: Creates a tensor filled with ones
- ```torch.rand```: Creates a tensor with random values uniformly sampled between 0 and 1
- ```torch.randn```: Creates a tensor with random values sampled from a normal distribution with mean 0 and variance 1
- ```torch.arange```: Creates a tensor containing the values
- ```torch.Tensor``` (input list): Creates a tensor from the list elements you provide

You can obtain the shape of a tensor in the same way as in numpy (```x.shape```), or using the ```.size``` method:

In [98]:
shape = x.shape
print("Shape:", x.shape)

size = x.size()
print("Size:", size)

dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


Tensor to Numpy, and Numpy to Tensor


In [99]:
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]])


In [100]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


Matrix multiplication

In [101]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [102]:
W = torch.arange(9).view(3, 3) # We can also stack multiple operations in a single line
print("W", W)

W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [103]:
h = torch.matmul(x, W) # Verify the result by calculating it by hand too!
print("h", h)

h tensor([[15, 18, 21],
        [42, 54, 66]])


 ### What about gpus?

When you create a tensor the tensor is ready to be computed by the cpu. To convert the tensor you can use ```.to()```
passing to the function "cuda" or "cpu" as needed

#### How do I know if I have cuda cores on my computer?
To solve this you can check with torch if cuda is available:

In [104]:
example_tensor = torch.rand(2,2)
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU for PyTorch.")
    example_tensor.to("cuda")
else:
    print("CUDA is not available. Using CPU for PyTorch.")
    example_tensor.to("cpu")

CUDA is not available. Using CPU for PyTorch.


### Exercises

#### 1. Create two tensors

   - A 3x3 tensor of random numbers.
   - A 3x3 tensor filled with ones.

In [105]:
#Exercise 1

randTensor = torch.rand(3, 3)
oneTensor = torch.ones(3, 3)

print(randTensor)
print(oneTensor)

tensor([[0.0606, 0.5414, 0.6403],
        [0.5293, 0.4150, 0.6887],
        [0.4374, 0.2539, 0.1915]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


#### 2. Perform the following operations

- Add the two tensors.
- Multiply the two tensors element-wise.
- Compute the dot product between the first row of both tensors.
 - Find the transpose of the resulting tensor from the element-wise multiplication.

In [106]:
#Exercise 2
sum =  torch.add(randTensor, oneTensor)
print(sum)

mul = torch.mul(randTensor, oneTensor)
print(mul)

dotP = torch.dot(randTensor.view(-1), oneTensor.view(-1))
print(dotP)

transpose = torch.transpose(mul, 0, 1)
print(transpose)

tensor([[1.0606, 1.5414, 1.6403],
        [1.5293, 1.4150, 1.6887],
        [1.4374, 1.2539, 1.1915]])
tensor([[0.0606, 0.5414, 0.6403],
        [0.5293, 0.4150, 0.6887],
        [0.4374, 0.2539, 0.1915]])
tensor(3.7581)
tensor([[0.0606, 0.5293, 0.4374],
        [0.5414, 0.4150, 0.2539],
        [0.6403, 0.6887, 0.1915]])


#### 3. Convert the resulting tensor to a NumPy array and back to a PyTorch tensor.

In [107]:
#Exercise 3

npArray = transpose.numpy()
print(npArray)

transAgain = torch.from_numpy(npArray)
print(transAgain)

[[0.06064802 0.5293475  0.43736166]
 [0.5413776  0.4150138  0.25391793]
 [0.6403236  0.68866366 0.19148952]]
tensor([[0.0606, 0.5293, 0.4374],
        [0.5414, 0.4150, 0.2539],
        [0.6403, 0.6887, 0.1915]])


## Autograd

1. Create Tensors

In [108]:
x_a = torch.tensor(0., requires_grad=True)
x_b = torch.tensor(0., requires_grad=True)
w_a = torch.tensor(0.9, requires_grad=True)
w_b = torch.tensor(0.9, requires_grad=True)

y = torch.tensor(0., requires_grad=False)



2. Build a computation graph

In [109]:
weighted_a = w_a * x_a
weighted_b = w_b * x_b
sum_unit = weighted_a + weighted_b



3. Activation Function

For a simple approach as ease of replication by hand we will this activation function:

In [110]:
y_hat = torch.sigmoid(sum_unit)


4. Calculate Loss

In [111]:
loss = torch.nn.BCELoss()
output = loss(y_hat, y)

5. Calculate gradients

In [112]:
output.backward()

6.Print out the gradients

In [113]:
print(x_a.grad)
print(x_b.grad)
print(w_a.grad)
print(w_b.grad)

tensor(0.4500)
tensor(0.4500)
tensor(0.)
tensor(0.)


### Training Loop

In [114]:
learning_rate = 0.1
epochs = 100

input_data = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
target_data = torch.tensor([[0], [0], [0], [1]], dtype=torch.float32)

In [115]:
class ANDGateModel(nn.Module):
    def __init__(self):
        super(ANDGateModel, self).__init__()
        self.linear = nn.Linear(2, 1,bias=True)

    def forward(self, x):
        x = self.linear(x)
        x = torch.sigmoid(x)
        return x


In [116]:
# Initialize the model
model = ANDGateModel()

# Loss function (Binary Cross-Entropy Loss)
loss_fn = torch.nn.BCELoss()

# Optimizer (Stochastic Gradient Descent)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(epochs):
    y_hat = model(input_data)
    loss = loss_fn(y_hat, target_data)


    loss.backward() # Backpropagation
    optimizer.step() # Update parameters using the optimizer
    optimizer.zero_grad() # Zero the gradients for the next iteration

    # Print loss and progress every 1000 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}/{epochs}, Loss: {loss.item():.4f}")

# Final weights and bias (optional)
print(f"Final weights: {model.linear.weight.data}")
print(f"Final bias: {model.linear.bias.data}")

# Test the AND gate
with torch.no_grad():
    for i in range(len(input_data)):
        x_a, x_b = input_data[i]
        y_hat = model(torch.tensor([[x_a, x_b]]))  # Model expects a batch
        print(f"Input: {input_data[i].numpy()} -> Predicted Output: {round(y_hat.item())}, Raw Output: {y_hat.item():.4f}")


Epoch 100/100, Loss: 0.1103
Final weights: tensor([[3.6861, 3.6935]])
Final bias: tensor([-5.5928])
Input: [0. 0.] -> Predicted Output: 0, Raw Output: 0.0037
Input: [0. 1.] -> Predicted Output: 0, Raw Output: 0.1302
Input: [1. 0.] -> Predicted Output: 0, Raw Output: 0.1294
Input: [1. 1.] -> Predicted Output: 1, Raw Output: 0.8565


!!! IMPORTANT: This example has a significant issue: the test set is the same as the training set.
This approach is used here solely for ease of explanation and should never be used in a production environment.!!!

### Exercises

#### 1.Replicate the OR Gate using a Neural Network
 Objective:
- Train a neural network to approximate the function of an OR gate.
- Compare how changing the weights or biases impacts the output of the network.

Input 1 | Input 2 | Output (OR)
| -- | -- | --|
0 | 0 | 0
0 | 1 | 1
1 | 0 | 1
1 | 1 | 1

1. Create the dataset
2. Replicate the architecture from the AND gate example
3. Change the loss function from Binary Cross-Entropy to Mean Squared Error

In [117]:
# Code Here

class ORGateModel(nn.Module):
    def __init__(self):
        super(ORGateModel, self).__init__()
        self.linear = nn.Linear(2, 1,bias=True)

    def forward(self, x):
        x = self.linear(x)
        x = torch.sigmoid(x)
        return x


In [118]:
# Initialize the model
model = ORGateModel()

# Loss function (Binary Cross-Entropy Loss)
loss_fn = torch.nn.MSELoss()

# Optimizer (Stochastic Gradient Descent)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(epochs):
    y_hat = model(input_data)
    loss = loss_fn(y_hat, target_data)


    loss.backward() # Backpropagation
    optimizer.step() # Update parameters using the optimizer
    optimizer.zero_grad() # Zero the gradients for the next iteration

    # Print loss and progress every 1000 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}/{epochs}, Loss: {loss.item():.4f}")

# Final weights and bias (optional)
print(f"Final weights: {model.linear.weight.data}")
print(f"Final bias: {model.linear.bias.data}")

# Test the AND gate
with torch.no_grad():
    for i in range(len(input_data)):
        x_a, x_b = input_data[i]
        y_hat = model(torch.tensor([[x_a, x_b]]))  # Model expects a batch
        print(f"Input: {input_data[i].numpy()} -> Predicted Output: {round(y_hat.item())}, Raw Output: {y_hat.item():.4f}")


Epoch 100/100, Loss: 0.0113
Final weights: tensor([[3.9011, 3.9587]])
Final bias: tensor([-5.9280])
Input: [0. 0.] -> Predicted Output: 0, Raw Output: 0.0027
Input: [0. 1.] -> Predicted Output: 0, Raw Output: 0.1225
Input: [1. 0.] -> Predicted Output: 0, Raw Output: 0.1164
Input: [1. 1.] -> Predicted Output: 1, Raw Output: 0.8735


In [119]:
# https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html

#### 2. Build and train a network
1. Build a simple fully connected neural network with the following architecture:
    - Input layer with 2 units
    - Hidden layer with 4 units and ReLU activation
    - Output layer with 1 unit
2. Define the following loss function and optimizer:
    - Loss: Mean Squared Error (MSE)
    - Optimizer: Stochastic Gradient Descent (SGD)

The network should mimic $y = 2x_1 + 3x_2$, where $x_1$ and $x_2$ are random inputs

In [120]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split

# Define the neural network
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        # Define layers here
        self.layer1 =   # Input to hidden layer
        self.activation_function =   # Activation function
        self.layer2 =   # Hidden to output layer

    def forward(self, x):
        # Define forward pass
        x =
        x =
        x =
        return x

# Create synthetic data
x = torch.rand(100, 2)
y = 2 * x[:, 0] + 3 * x[:, 1]
y = y.view(-1, 1)

# Split data into training and test sets (80% train, 20% test)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Initialize the model, loss function, and optimizer
model = SimpleNet()
criterion =   # Loss function (MSE)
optimizer =   # Optimizer (SGD)

# Training loop
for epoch in range(100):
    model.train()

    # Forward pass
    y_pred = model(x_train)

    # Compute loss
    loss =   # Compute loss using criterion

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

model.eval()  # Set the model to evaluation mode
with torch.no_grad():
    y_test_pred = model(x_test)  # Get predictions for the test set
    test_loss = criterion(y_test_pred, y_test)  # Compute test loss

    print(f'Test Loss: {test_loss.item()}')

# Show some final predictions
print("Final Predictions (first 5 test samples):")
for i in range(5):
    print(f"Predicted: {y_test_pred[i].item():.4f}, Actual: {y_test[i].item():.4f}")



SyntaxError: invalid syntax (1415340237.py, line 11)